#!/bin/bash
set -e

cargo build --release --features generate --locked --target-dir target
scripts/mkmo locale/
strip target/release/paru

tar --zstd -cf paru.tar.zst man completions paru.conf locale -C target/release paru

